/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package elections;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        assertTrue("Should return 'true'", true);
    }
}
